//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clientMonitoring.MonitoringReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataLogs", Namespace="http://schemas.datacontract.org/2004/07/VelibSoapService")]
    [System.SerializableAttribute()]
    public partial class DataLogs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numberOfAPIRequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numberOfClientRequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numberOfRequestField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numberOfAPIRequest {
            get {
                return this.numberOfAPIRequestField;
            }
            set {
                if ((this.numberOfAPIRequestField.Equals(value) != true)) {
                    this.numberOfAPIRequestField = value;
                    this.RaisePropertyChanged("numberOfAPIRequest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numberOfClientRequest {
            get {
                return this.numberOfClientRequestField;
            }
            set {
                if ((this.numberOfClientRequestField.Equals(value) != true)) {
                    this.numberOfClientRequestField = value;
                    this.RaisePropertyChanged("numberOfClientRequest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numberOfRequest {
            get {
                return this.numberOfRequestField;
            }
            set {
                if ((this.numberOfRequestField.Equals(value) != true)) {
                    this.numberOfRequestField = value;
                    this.RaisePropertyChanged("numberOfRequest");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MonitoringReference.IMonitoringService")]
    public interface IMonitoringService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/GetNumberOfRequest", ReplyAction="http://tempuri.org/IMonitoringService/GetNumberOfRequestResponse")]
        int GetNumberOfRequest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/GetNumberOfRequest", ReplyAction="http://tempuri.org/IMonitoringService/GetNumberOfRequestResponse")]
        System.Threading.Tasks.Task<int> GetNumberOfRequestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/GetNumberOfClients", ReplyAction="http://tempuri.org/IMonitoringService/GetNumberOfClientsResponse")]
        int GetNumberOfClients();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/GetNumberOfClients", ReplyAction="http://tempuri.org/IMonitoringService/GetNumberOfClientsResponse")]
        System.Threading.Tasks.Task<int> GetNumberOfClientsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/GetNumberOfRequestToAPI", ReplyAction="http://tempuri.org/IMonitoringService/GetNumberOfRequestToAPIResponse")]
        int GetNumberOfRequestToAPI();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/GetNumberOfRequestToAPI", ReplyAction="http://tempuri.org/IMonitoringService/GetNumberOfRequestToAPIResponse")]
        System.Threading.Tasks.Task<int> GetNumberOfRequestToAPIAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/GetLogs", ReplyAction="http://tempuri.org/IMonitoringService/GetLogsResponse")]
        clientMonitoring.MonitoringReference.DataLogs GetLogs(System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/GetLogs", ReplyAction="http://tempuri.org/IMonitoringService/GetLogsResponse")]
        System.Threading.Tasks.Task<clientMonitoring.MonitoringReference.DataLogs> GetLogsAsync(System.DateTime start, System.DateTime end);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMonitoringServiceChannel : clientMonitoring.MonitoringReference.IMonitoringService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonitoringServiceClient : System.ServiceModel.ClientBase<clientMonitoring.MonitoringReference.IMonitoringService>, clientMonitoring.MonitoringReference.IMonitoringService {
        
        public MonitoringServiceClient() {
        }
        
        public MonitoringServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonitoringServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitoringServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitoringServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetNumberOfRequest() {
            return base.Channel.GetNumberOfRequest();
        }
        
        public System.Threading.Tasks.Task<int> GetNumberOfRequestAsync() {
            return base.Channel.GetNumberOfRequestAsync();
        }
        
        public int GetNumberOfClients() {
            return base.Channel.GetNumberOfClients();
        }
        
        public System.Threading.Tasks.Task<int> GetNumberOfClientsAsync() {
            return base.Channel.GetNumberOfClientsAsync();
        }
        
        public int GetNumberOfRequestToAPI() {
            return base.Channel.GetNumberOfRequestToAPI();
        }
        
        public System.Threading.Tasks.Task<int> GetNumberOfRequestToAPIAsync() {
            return base.Channel.GetNumberOfRequestToAPIAsync();
        }
        
        public clientMonitoring.MonitoringReference.DataLogs GetLogs(System.DateTime start, System.DateTime end) {
            return base.Channel.GetLogs(start, end);
        }
        
        public System.Threading.Tasks.Task<clientMonitoring.MonitoringReference.DataLogs> GetLogsAsync(System.DateTime start, System.DateTime end) {
            return base.Channel.GetLogsAsync(start, end);
        }
    }
}
